### ISSUE TITLE
NSUserDefaults does not have a member named 'subscript'

### ISSUE THREAD

**Issue by sebastiaanluca** [phimage/Prephirences#1]
Don't know if I'm doing something wrong here, but just tried the example and it throws an error.

``` swift
let userDefaults = NSUserDefaults.standardUserDefaults()

if let myValue = userDefaults["mykey"] as? Bool {..}
```

> NSUserDefaults does not have a member named 'subscript'

If I use `objectForKey`, it works.

``` swift
let userDefaults = NSUserDefaults.standardUserDefaults()

if let myValue = userDefaults.objectForKey("mykey") as? Bool {..}
```

Same situation when trying to modify it. `userDefaults["mykey"] = "myvalue"` does not work.

**Comment by phimage** [comment]
`objectForKey` is standard method of `NSUserDefaults` class, work without using Prephirences framework
Did you use cocoapod? and import the framework in your file?

``` swift
import Prephirences
```

For information `subscript`  for `NSUserDefaults` is defined in `NSUserDefaults+Prephirences.swift`

**Comment by sebastiaanluca** [comment]
The import was the solution! Thought it was a Swift extension of NSUserDefaults, so I could use it without importing anything. Now I can successfully use `return self.userDefaults[key]` and `return self.userDefaults[key]?[preference]`. Thanks!

PS: maybe add it to the readme? For us noobs ;)
