### ISSUE TITLE
Xcode 9 GM/Swift 4 issues

### ISSUE THREAD

**Issue by jyounus** [phimage/Prephirences#14]
Hey there,

Could you please update this lib for Swift 4? Currently there are build errors. 

Thanks

**Comment by phimage** [comment]
I will do it. Maybe this week end

**Comment by phimage** [comment]
just pushed this f6b8f2c4848f143a51d32ffd60cd123b80b7703a

**Comment by jyounus** [comment]
Hey @phimage, 

I just tried it and uncommented the code I previous had to comment out to get the project compiling. Now it seems to work just fine again! :D

Thanks!

**Comment by phimage** [comment]
Good to know
You are welcome

I will close the issue after the version tag and cocoapod release

**Comment by jyounus** [comment]
Hey, could you release v4.0.0 on cocoapods please? I'm currently going through my project updating my pods to the latest versions/trying to use the official releases rather than pointing to specific commits but this lib still hasn't got a Swift 4 release yet. The code is there, but just needs releasing now.

Would be great if you could do that. Thanks :)

**Comment by phimage** [comment]
done
