### ISSUE TITLE
Minor typo in readme

### ISSUE THREAD

**Issue by thecodewarrior** [phimage/Prephirences#15]
I just noticed a typo in the readme and thought I'd point it out as opposed to assuming "someone else will do it."

Under `Transformation and Archiving` you have `substrict` where you likely meant `subscript`.

**Comment by phimage** [comment]
thanks @thecodewarrior do not hesitate to make a PR. You can edit readme on github and submit your modification

**Comment by jyounus** [comment]
I went ahead and created a PR for this: https://github.com/phimage/Prephirences/pull/18
