### ISSUE TITLE
Logo.png is part of the compiled framework

### ISSUE THREAD

**Issue by jyounus** [phimage/Prephirences#16]
Hey there,

I've noticed that when I compile my project and check the IPA file (extract it), the Prephirences.framework file has the Logo.png file inside of it. 

It's not a big deal, but would be great if it could be excluded. I've included a screenshot. I'm using this with Cocoapods. 

EDIT:
I'm assuming the logo isn't needed, which is why I've opened this "issue".

Thanks

![Screenshot](https://abload.de/img/prephirencesa1rj2.jpeg)

**Comment by phimage** [comment]
Could you PR?
I think podspec must be edited to remove the resource
I will make a new tag next week

**Comment by jyounus** [comment]
Will have a PR for you by tomorrow.

Sent from my iPhone

On 26 May 2018, at 22:37, Eric Marchand <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you PR?
I think podspec must be edited to remove the resource
I will make a new tag next week

**Comment by jyounus** [comment]
I see you've released a new version of the cocoapod lib. Thanks! :D
