### ISSUE TITLE
Unable to store to keychain

### ISSUE THREAD

**Issue by jyounus** [phimage/Prephirences#19]
Hey there,

This was working fine for me previously, but now that I've started to prepare my project for appstore release (creating separate environment for dev/staging/prod as well as having different app id's for each of them), I'm unable to store strings in the keychain....

I'm not sure what I'm missing. It works fine if I save to lets say user defaults, but for some reason it stopped working saving to the keychain.

Is there anything you can think of that needs to be enabled in order to use the keychain? Am I missing some entitlements (Keychain Sharing is turned off, since I don't want to share items that I store)?

Sorry I know this most likely has nothing to do with your code, but hoping you can help me out. I've tried to Google this and wasted all day today to figure this out but I'm not getting anywhere.

Thanks

**Comment by jyounus** [comment]
I managed to get to the bottom of this issue. Using subscripts like this doesn't return the correct value for me, it returned nil.
```
keychain["key"] = "some string"
print(keychain["key"]) // nil
```

Instead I have to use this now:
```
keychain.set("some string", forKey: "key")
print(keychain.string(forKey: "key")) // some string
```

I've no idea why this only stopped working just recently. Not sure if there's something wrong with this lib or if it's just my project. I will close this issue, but feel free to investigate if it might be an issue with the lib. 

I should also mention that I added CryptoPrephirences to my Xcode project. This obviously doesn't work now, so I reverted to my own manual implementation to encrypt/decrypt before saving/retrieving from the keychain.

**Comment by phimage** [comment]
I reopen the issue
I will work on keychain. This is an old code, which has been converted from swift 2 without any test...

So I will make unit test and fix the issues

**Comment by phimage** [comment]
On macOS it is fixed
- code factorized
- a lot of AnyObject converted to Any
- keychain unit test implemented
  - unit test will be now compatible with macOS, not only iOS
  - I am not able to test on iOS using Xcode Unit test
keychain write failed on simulator and test. (I read a lot about xamarin, entitlements.plist file, ...)
- start to implement internet password
- allow to get keychain attribute information (creation date, modification date, etc...)

So I am not sure that iOS implementation is working
I must create a real app before merging in master branch

---

to have `String` using `subscript`
```swift
print(keychain[string: "key"]) // same as keychain.string(forKey: "key")
```

**Comment by jyounus** [comment]
Nice one! Would be great if that new syntax you posted above would work, and a new version could be pushed. :)

**Comment by phimage** [comment]
I merge in master branch and make a new release
but I test only on mac os

**Comment by phimage** [comment]
I make unit test on macOS with new release for swift 4.2
