### ISSUE TITLE
Example App?

### ISSUE THREAD

**Issue by MikeManzo** [phimage/Prephirences#3]
Not an issue ... 

Great framework!  Any chance you have (or know of) a sample application that use prephirences?  it would be great to see how you use this in practice (beyond the snippets in the Read Me).

Thanks!

**Comment by phimage** [comment]
Ok I will think about adding sample projects

Currently in my project I do something like that in `AppDelegate`, at file scope to have an access everywhere to `Preferences` variable

``` swift
...
import Prephirences

let UserDefaults = NSUserDefaults.standardUserDefaults()
let AppConfig = DictionaryPreferences("Preferences", ofType: "plist")! // read only preference defined in Preferences.plist resource
let Preferences: MutableCompositePreferences = [AppConfig, UserDefaults]
// Prephirences.sharedInstance = Preferences // uncomment to give access to Preferences without using the global variable

class AppDelegate: ...
```
