### ISSUE TITLE
Compilation error by Xcode7.0 beta6.

### ISSUE THREAD

**Issue by chenjsa** [phimage/Prephirences#4]
Hi,
    I integrated prephirences into my project by cocopoads, the code is pod 'Prephirences', :git => 'https://github.com/phimage/Prephirences.git', :branch => '2.0.0'.
   Now in Xcode7.0 beta6 i get a compilation error. Type 'Bool' does not comform to protocol 'LogicalOperationsType', in Preference.swift line 256.
   I don't know how to fix it, could you please help me?
Thank you!

**Comment by phimage** [comment]
Ok I have not already updated my xcode 7, I will fix after updated (PR is welcome)

`LogicalOperationsType` in my code

``` swift
    func && (left: Self, @autoclosure right:  () -> Self) -> Self // AND
    func || (left: Self, @autoclosure right:  () -> Self) -> Self // OR
    prefix func ! (left: Self) -> Self // NOT
```

Bool must not in beta6 implement this operators, maybe change into methods signature

**Comment by phimage** [comment]
Now Bool implement operator with closure that can throw exception

``` swift
func && (left: Self, @autoclosure right:  () throws -> Self) rethrows -> Self // AND
func || (left: Self, @autoclosure right:  () throws -> Self) rethrows -> Self // OR
```

I fixed some others errors
