### ISSUE TITLE
Won't compile with Xcode 7.3 beta 2 / Swift 2.2

### ISSUE THREAD

**Issue by rshev** [phimage/Prephirences#7]
That's pretty much it.
Multiple **Operations must have one or two arguments** and warnings on stuff to be deprecated in Swift 3.0

**Comment by phimage** [comment]
ok I will download the beta, thanks

**Comment by phimage** [comment]
fix into swift2.2 branch
"var args" don't know how to call it in swift `...` no more allowed with `+=` operator
