### ISSUE TITLE
Xcode 7.3 & Swift 2.2

### ISSUE THREAD

**Issue by jyounus** [phimage/Prephirences#8]
Hey,

Now that both of them are officially released, are you planning to merge the Swift 2.2 branch into master and push a new update to Cocoapods any time soon? Or are there some issues that you still need to sort out first?

Thanks

**Comment by phimage** [comment]
Already done, no?

**Comment by jyounus** [comment]
Oh okay. I guess that's my fault then. I must have pulled the wrong version in my pod file. 

I've you've already merged it, please ignore this! My bad!
